version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
    time: "10:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: workbox-webpack-plugin
    versions:
    - 6.0.2
    - 6.1.0
  - dependency-name: webpack-cli
    versions:
    - 4.3.1
    - 4.4.0
  - dependency-name: webpack
    versions:
    - 5.11.1
    - 5.19.0
  - dependency-name: "@sentry/browser"
    versions:
    - 5.29.2
    - 6.0.3
  - dependency-name: worker-loader
    versions:
    - 3.0.7
  - dependency-name: webpack-dev-server
    versions:
    - 3.11.1
  - dependency-name: libheif-js
    versions:
    - 1.10.0
